### ISSUE TITLE
Organ limits don't appear to work

### ISSUE THREAD

**Issue by jamespicone** [soolar/CONSUME.ash#12]
```
> get valueOfAdventure

3400

> CONSUME ORGANS 15 21 14

Your ideal diet: acquire 1 milk of magnesium; acquire 3 Ol' Scratch's salad fork; acquire 7 Frosty's frosty mug; acquire 3 extra-greasy slider; acquire 2 chocolate pasta spoon; acquire 6 beastly paste; acquire 5 octolus oculus; acquire 7 perfect cosmopolitan; acquire 1 Gnollish sangria; acquire 3 Special Seasoning; checkpoint; cast 2 The Ode to Booze; use milk of magnesium; maximize hp,10cold res,10hot res; drink Gnollish sangria; chew 3 beastly paste; chew 2 octolus oculus; eat 3 Ol' Scratch's salad fork; eat 3 extra-greasy slider; drink 7 Frosty's frosty mug; drink 7 perfect cosmopolitan; chew 3 beastly paste; chew 3 octolus oculus; use 2 chocolate pasta spoon; familiar Hobo Monkey; outfit checkpoint;
This should cost roughly 352,994 meat
Adventure yield should be roughly 394-442
That's an average profit of 1,111,356
Including adventures you already have, you should profit 1,651,956 today
In total, you're filling up 15 fullness, 22 liver, and 29 spleen
```

Note that 'chew 3 beastly paste; chew 3 octolus oculus' will give 15 spleen; the diet ends with that line so it's guaranteed to result in 15 spleen used total at the end. Perhaps I'm misinterpreting how the limit is meant to work? It appears to be a limit applied prior to spleen cleaning.

**Comment by soolar** [comment]
Okay, I finally fixed this. I only hadn't done it already because I wasn't really happy with the fix, but I guess an imperfect fix is better than no fix (for now anyway). At some point I'd like to come back and make it fully fill organs before cleaning them regardless of limits, instead of absolutely never going over the limit, since that would be more optimal. But eh.
